on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'oscal'
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    branches:
      - main
permissions:
  contents: write
name: Generate Baseline Catalogs with Profiles
env:
  OSCAL_DIR_PATH: vendor/oscal
  CICD_DIR_PATH: vendor/oscal/build/ci-cd
  CONTENT_CONFIG_PATH: src/config
  SAXON_VERSION: 9.9.0-1
jobs:
  validate-and-publish-content:
    name: Generate Agency Baselines
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code and content
        uses: actions/checkout@v2
        with:
          path: git-content
          submodules: recursive
      - name: Update APT package metadata
        run: |
          sudo rm -rf /var/lib/apt/lists/* && sudo apt-get update
      - name: Install APT dependencies
        run: |
          sudo apt-get install libxml2-utils
      - name: Install NPM dependencies
        run: |
          sudo npm install --loglevel verbose -g yargs ajv-formats@"^1.5.x" ajv-cli@"^4.0.x" yaml-convert@"^1.0.x"
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Get Saxon-HE
        run: |
          mvn org.apache.maven.plugins:maven-dependency-plugin:2.10:get -DartifactId=Saxon-HE -DgroupId=net.sf.saxon -Dversion=$SAXON_VERSION
      - name: Validate Content
        run:
          bash "${GITHUB_WORKSPACE}/git-content/${CICD_DIR_PATH}/validate-content.sh" -v -o "${GITHUB_WORKSPACE}/git-content/${OSCAL_DIR_PATH}" -a "${GITHUB_WORKSPACE}/git-content" -c "${GITHUB_WORKSPACE}/git-content/${CONTENT_CONFIG_PATH}"
      - name: Auto-convert content
        run:
          bash "${GITHUB_WORKSPACE}/git-content/${CICD_DIR_PATH}/copy-and-convert-content.sh" -v -o "${GITHUB_WORKSPACE}/git-content/${OSCAL_DIR_PATH}" -a "${GITHUB_WORKSPACE}/git-content" -c "${GITHUB_WORKSPACE}/git-content/${CONTENT_CONFIG_PATH}" -w "${GITHUB_WORKSPACE}/git-content/dist" --resolve-profiles
      - name: Upload updated content to repo
        uses: stefanzweifel/git-auto-commit-action@v4.4.1
        if: github.ref == 'refs/heads/main'
        with:
          repository: git-content
          commit_message: Publishing auto-converted artifacts
          commit_user_name: OSCAL GitHub Actions Bot
          commit_user_email: oscal@nist.gov
          commit_author: OSCAL GitHub Actions Bot <oscal@nist.gov>
